version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatbot
    networks:
      - internal-network

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
